### ISSUE TITLE
Consider re-using F5, F10, F11 debugging keyboard shortcuts as an option

### ISSUE THREAD

**Issue by dngoins** [Microsoft/RTVS#1261] opened 2016-03-12 03:48 UTC
Have an option to use the standard F5, F10, F11 keyboard shortcuts for .Net Devs trying out R

**Comment by int19h** [comment] 2016-03-12 04:49
Step Over (F10) and Step Into (F11) should already work, unless you're using the Data Science profile with RStudio keybindings.

"Step Out" doesn't work currently - it was deliberately disabled, because there are a number of limitations around step-out functionality in R itself that result in very confusing behavior for someone used to how it works in C# or Python (#1028 and #975 are two examples). We're investigating possible workarounds. 

We will definitely wire up F5. The only reason why it's not there yet is because we wanted to have parity with RStudio way of doing things, whereas F5 is something different in VS (it implies launching a specific file from the active project). This is tracked by #1090.

**Comment by jflam** [comment] 2016-03-18 17:59
Dupe of #1090

**Closed by jflam** 2016-03-18 17:59 UTC
