### ISSUE TITLE
RMarkdown publishing not working on either local or remote scenarios

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2909] opened 2016-12-16 23:23 UTC
I'm seeing this when trying to preview HTML and PDF for a `.rmd` file

![image](https://cloud.githubusercontent.com/assets/8877/21281678/917d7e50-c3a3-11e6-8b70-36248a057dbf.png)

**Comment by jflam** [comment] 2016-12-16 23:30
I installed CRAN R 3.3.2, and I see this:

![image](https://cloud.githubusercontent.com/assets/8877/21281793/883d978e-c3a4-11e6-99b5-1ba0d2cfed8a.png)

**Comment by jflam** [comment] 2016-12-17 00:19
I get a repro of this on my desktop as well, using a different version of R and fresh installs of rmarkdown package and Pandoc.

**Comment by jflam** [comment] 2016-12-17 00:26
Repros on Mikhail's machine now. 3 repros.

**Comment by MikhailArkhipov** [comment] 2016-12-17 00:45
This is exception from `readBin()`. For some reason it tries to open file as text (`rt`).`Connection` has nothing to do with remote, it is the first parameter to the `readBin`

**Comment by MikhailArkhipov** [comment] 2016-12-17 01:04
The issue is coming from `rmarkdown:render` and in fact, it is broken in RS too

![image](https://cloud.githubusercontent.com/assets/12820357/21283104/c1314862-c3b1-11e6-8e0d-f0760c4b6419.png)

**Comment by MikhailArkhipov** [comment] 2016-12-17 01:06
![image](https://cloud.githubusercontent.com/assets/12820357/21283116/fddbebbe-c3b1-11e6-90ad-0201ec819274.png)

**Comment by MikhailArkhipov** [comment] 2017-01-10 22:33
I believe this was resolved by adding `~/` to the file path.

**Comment by MikhailArkhipov** [comment] 2017-01-11 16:19
Closing for now

**Closed by MikhailArkhipov** 2017-01-11 16:19 UTC
