### ISSUE TITLE
Encoding problem with Chinese characters

### ISSUE THREAD

**Issue by renkun-ken** [Microsoft/RTVS#1288] opened 2016-03-17 09:09 UTC
In RStudio, the locale works fine:

```
> Sys.setlocale(locale = "Chinese")
[1] "LC_COLLATE=Chinese (Simplified)_China.936;LC_CTYPE=Chinese (Simplified)_China.936;LC_MONETARY=Chinese (Simplified)_China.936;LC_NUMERIC=C;LC_TIME=Chinese (Simplified)_China.936"
> df <- data.frame(x = "你好")
> df
     x
1 你好
```

The interactive console, environment explorer, and data frame viewer all work with the correct locale.

But with RTVS, although there's no problem showing a variable in the console:

```
> Sys.setlocale(locale = "Chinese")
[1] "LC_COLLATE=Chinese (Simplified)_China.936;LC_CTYPE=Chinese (Simplified)_China.936;LC_MONETARY=Chinese (Simplified)_China.936;LC_NUMERIC=C;LC_TIME=Chinese (Simplified)_China.936"
> x <- "你好"
> x
[1] "你好"
```

The value of the variable is shown as `ÄãºÃ` in the variable explorer and the locale does not seem to work for data frame in R Interactive:

```
> data.frame(x=x)
     x
1 ÄãºÃ
```

**Comment by int19h** [comment] 2016-03-18 19:01
Dupe of #1268, except for Variable Explorer part, so I'll add that to the other bug and close this one.

**Closed** 2016-03-18 19:01 UTC
Labels: priority:P1, type:bug
