### ISSUE TITLE
RTVS RC1 Errors and Latest PTVS

### ISSUE THREAD

**Issue by marabout2015** [Microsoft/RTVS#3244] opened 2017-02-28 17:04 UTC
I use both RTVS and PTVS. If after starting Visual Studio 2015 I use a Python Interactive window before I use an R Interactive window, I get an error report, and then I cannot use R Interactive without restarting Visual Studio. This is true across three systems: a Lenovo ThinkPad, a Surface Pro 3, and a Data Science Virtual Machine. I have attached my Visual Studio configuration, a snip of the error dialog, and the file referred to in the error dialog.

[Visual Studio configuration.txt](https://github.com/Microsoft/RTVS/files/807567/Visual.Studio.configuration.txt)
![exception](https://cloud.githubusercontent.com/assets/17052626/23415699/0c18579a-fdae-11e6-8c14-0a55226df231.PNG)

**Comment by MikhailArkhipov** [comment] 2017-02-28 17:37
Could you please attach that log file that the message box shows? It should contain information on the exception specifics. Thanks.

**Comment by MikhailArkhipov** [comment] 2017-03-01 22:05
If this is specific to PTVS + RTVS combination and the interactive window, the issue is being fixed in VS 2017. Unfortunately, there is no update to VS 2015 interactive window component. Nevertheless, it would be useful to look into the log file.

**Comment by MikhailArkhipov** [comment] 2017-03-06 22:04
Might be same as #3259

**Comment by AlexanderSher** [comment] 2017-03-07 01:35
Yep, stacks are identical

**Closed** 2017-03-07 17:20 UTC
Labels: area:Editor, RC3, type:bug
