### ISSUE TITLE
R Interactive window doesn't work

### ISSUE THREAD

**Issue by Norticaranda** [Microsoft/RTVS#1606] opened 2016-04-17 11:28 UTC
Hi
I followed the installation guide and now in my Visual Studio 2015 community Update 2, when créate a new R Project the R interactive Windows don't load the prompt. I try to reset whis interactive sesión and show "Starting R sesión..." but dosen't happend

I installed all prerequisites and in R options the 64 bit parameter has "C:\Program Files\Microsoft\MRO\R-3.2.3"

The R Variable Window show "No R interactive"

Any idea? Thank's

**Comment by smortaz** [comment] 2016-04-17 14:36
hi, to confirm:

1. you installed VS 2015 + update2
2. you installed RTVS 0.2 from:



   - Download R Tools for Visual Studio <https://aka.ms/rtvs-current>

do you see an "R Tools" option in the top level VS menu?

**Comment by Norticaranda** [comment] 2016-04-17 16:29
Yes i installed visual studio 2015 update 2
Yes i installed RTVS 0.2
And yes I have R Tools like option in top level 

I reinstall all again, bug everything remains the same

**Comment by smortaz** [comment] 2016-04-17 17:59
ok.  and R Tools | Windows | R interactive doesnt do anything?

to double check - have you installed R?

what does R Tool | Options say about the location or R?

does Rgui or Rstudio run?

if still having trouble, please send logs:  R Tools | Feedback | Send Frown.

thanks.

**Comment by Norticaranda** [comment] 2016-04-17 18:42
I installed the 3.2.3 of R for Windows from https://www.r-project.org/
In R tools | Options i have the path "C:\Program Files\Microsoft\MRO\R-3.2.3" about R location
MRO Rgui 3.2.3 64 bits run ok. R Console and R Script.

I open a Frown to Microsoft with this issue. If I get help and solve the problem I will tell

**Comment by int19h** [comment] 2016-04-17 19:39
It could be #1432.

**Comment by int19h** [comment] 2016-04-17 19:40
Can you check if R.exe is somewhere in your `PATH`?

**Comment by MikhailArkhipov** [comment] 2016-04-18 22:21
Probable duplicate of issue fixed in 0.3. For verification.

**Comment by Norticaranda** [comment] 2016-04-19 06:34
Hi Mikhail 
 
I solved the problem, but I don't know how.
 
I supose that the problem was Microsoft R  Open (the R distribution). I reinstall again with all default options and it worked
Any option in the install wizard causes the problem
 
Thanks all for help

 
Date: Mon, 18 Apr 2016 15:21:53 -0700

**Closed** 2016-04-19 06:36 UTC
Labels: area:REPL-Backend, type:bug

**Comment by MikhailArkhipov** [comment] 2016-04-19 16:27
OK, it does appear to be the issue we have fixed. Reinstall probably placed correct R on the path in position that allowed RTVS to fetch it first.
