### ISSUE TITLE
dead REPL after remote pkg install

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#2285] opened 2016-09-09 21:42 UTC
![image](https://cloud.githubusercontent.com/assets/742484/18403774/ab6a43fc-769b-11e6-8837-28b1ffe976b8.png)

![image](https://cloud.githubusercontent.com/assets/742484/18403753/87eaa02a-769b-11e6-90ae-dbe706ea80ac.png)

**Comment by int19h** [comment] 2016-09-09 23:12
Broker-side logs (for both broker and host) do not indicate any issues. At the same time, there were intermittent network connectivity issues during the bash, so it is very likely that connection was simply dropped because of them. 

So this is likely by design, but we might want to make the error messages here clearer - probably by walking the `InnerException` chain beginning with `RHostDisconnectedException` in logging code, and printing out any inner error messages.

**Comment by MikhailArkhipov** [comment] 2016-09-12 21:00
@AlexanderSher : does #2295 fix this by any chance?

**Comment by AlexanderSher** [comment] 2016-09-12 21:53
I was never able to repro it. @smortaz, did you get your packages installed on the remote machine?

**Comment by smortaz** [comment] 2016-09-12 22:52
at this point lets wait for the new round of fixes & i'll try again.

**Comment by int19h** [comment] 2016-10-14 20:58
@smortaz Did you see this lately?

**Comment by MikhailArkhipov** [comment] 2016-10-24 16:33
Closing - reactivate if still reproes.

**Closed by MikhailArkhipov** 2016-10-24 16:33 UTC
Labels: area:Remote
