### ISSUE TITLE
legend function creates strange sized legend on high DPI display.

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#2017] opened 2016-06-28 00:26 UTC
Following command produces 
```R
plot(1)
legend("topleft", legend = "some text", pch = 1)
```
![legend](https://cloud.githubusercontent.com/assets/3863577/16399927/b65091f4-3d11-11e6-8d99-40d17344de5c.png)

whereas MRO produces

![mro](https://cloud.githubusercontent.com/assets/3863577/16399941/e0f1248c-3d11-11e6-8dcf-880eacf00ae5.png)

**Comment by huguesv** [comment] 2016-07-07 00:24
Thanks for the report. I will investigate.

**Comment by huguesv** [comment] 2016-07-11 20:36
Thanks Marchen!

This happens when the RTVS graphics device is created before the Plot window is created (and windows dpi setting > 100%).

Workaround is to show the plot window (R Tools->Windows->Plots) and reset the interactive window immediately after.

Some details:

When the RTVS graphics device doesn't have `width`, `height`, `res` to use when initializing (because plot window hasn't been created), it uses default size and default dpi of 96.

When the plot window finally appears, the dimensions and resolution are sent to the graphics device, which uses them when creating the `png`.

The problem is that it isn't updating the RTVS graphics device descriptor, which has point size, clip rectangles and other values that were calculated based on the original 96dpi default.

I will have a fix shortly.

**Comment by huguesv** [comment] 2016-09-08 17:38
Fixed in 0.5.  If you issue a plot command and the plot window hasn't been created yet, the window will be created first, the window size will be used to initialize the graphics device, which will then render the plot at the correct size.  So no extra resize will happen, which is what makes the legends go bad.

**Closed by huguesv** 2016-09-08 17:38 UTC
Labels: area:Plotting, type:bug

**Comment by Marchen** [comment] 2016-09-10 09:28
Thanks for the fix! I'm awaiting to see 0.5!
