### ISSUE TITLE
Repeating diagnostic messages

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1165] opened 2016-03-01 23:18 UTC
From user:

Yes, still getting this bug. Now it’s the result of running build_vignettes() on my dplyrXdf package source (I believe I’ve supplied you guys with this already).

``` 
> build_vignettes("../dplyrXdf")
Installing 2 packages: digest, knitr
package ‘digest’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘digest’
package ‘knitr’ successfully unpacked and MD5 sums checked
Building dplyrXdf vignettes
Loading required package: dplyr
 
Attaching package: 'dplyr'
The following objects are masked from 'package:stats':
    filter, lag

The following objects are masked from 'package:base':
    intersect, setdiff, setequal, union
 
Moving dplyrXdf_intro.html, dplyrXdf_user.html, dplyrXdf_intro.R, dplyrXdf_user.R to inst/doc/
Copying dplyrXdf_intro.Rmd, dplyrXdf_user.Rmd to inst/doc/
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\airports.xdf' cannot be found.
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\flights_rx1.xdf' cannot be found.
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\flights_rx2.xdf' cannot be found.
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\flights_rx3.xdf' cannot be found.
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\flights.xdf' cannot be found.
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\flights.xdf' cannot be found.
> traceback()
No traceback available 
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\airports.xdf' cannot be found.
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\flights_rx1.xdf' cannot be found.
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\flights_rx2.xdf' cannot be found.
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\flights_rx3.xdf' cannot be found.
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\flights.xdf' cannot be found.
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\flights.xdf' cannot be found.
> 
> sdfs
Error: object 'sdfs' not found
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\airports.xdf' cannot be found.
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\flights_rx1.xdf' cannot be found.
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\flights_rx2.xdf' cannot be found.
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\flights_rx3.xdf' cannot be found.
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\flights.xdf' cannot be found.
 
The file or directory 'C:\Users\hongooi\Documents\dplyrXdf\dplyrXdf\vignettes\flights.xdf' cannot be found.
> 
```

**Comment by int19h** [comment] 2016-03-10 22:06
Need to debug to figure out the root cause to cost. But likely suspect is the same as #943 (i.e. variables left around which are bound to files that no longer exist), in which case it is a dupe.

**Comment by int19h** [comment] 2016-03-15 22:29
Closing as dupe of  #943.

**Closed by int19h** 2016-03-15 22:29 UTC
Labels: area:REPL-Backend, priority:P2, type:bug
