### ISSUE TITLE
Data Science Settings leaves old developer toolbars behind

### ISSUE THREAD

**Issue by revodavid** [Microsoft/RTVS#2537] opened 2016-10-19 16:31 UTC
Updated to VS Community 2015 Update 3 and installed RTVS 0.5

Ran "R Tools > Daya Science Settings" expecting to get the toolbar layout depicted in the [Install Guide](https://microsoft.github.io/RTVS-docs/installation.html).

Instead, my toolbar looks like this:
![image](https://cloud.githubusercontent.com/assets/152948/19527911/8419dd6c-95ef-11e6-8a0c-752d8509873e.png)

**Comment by MikhailArkhipov** [comment] 2016-10-19 17:14
I don't think we provide toolbar layout, only window layout.

**Comment by MikhailArkhipov** [comment] 2016-12-03 23:27
VS has no ability for the window layout to say 'close everything but this' (i.e. whitelist case). It does not touch windows that particular layout does not know about or were opened by the user. For example, if you open C# interactive and reset window layout, the window will not be closed. Similarly, if some other team adds a new toolbar in Update N, it will appear as DS layout does not explicitly say 'close it'.

So effectively this is by design.

**Closed** 2016-12-04 19:52 UTC
