### ISSUE TITLE
Select R Interpreter

### ISSUE THREAD

**Issue by kesso1** [Microsoft/RTVS#3265] opened 2017-03-06 07:20 UTC
How can you define the R Interpreter for an R Remote Workspace manually? Didn't find anything in the Microsoft.R.Host.Broker.Config.json or Microsoft.R.Host.UserProfile.exe.config...

**Comment by smortaz** [comment] 2017-03-06 07:28
hi - did you see the docs:
http://microsoft.github.io/RTVS-docs/remote-execution.html

**Comment by kesso1** [comment] 2017-03-06 07:33
I did, but can't find a section to configure the r interpreter on the remote workspace server.

**Comment by smortaz** [comment] 2017-03-06 07:40
ah ok.  basically click on the cog wheel:

![image](https://cloud.githubusercontent.com/assets/742484/23600717/d583a614-01fc-11e7-90c0-09969b8c7bf0.png)

and enter the values in the fields (descriptive name, machine name, etc.)

a good write up is here:

http://blogs.u2u.be/u2u/post/2017/03/02/Using-Azure-VMs-as-remote-R-workspaces-in-R-Tools-for-Visual-Studio.aspx

towards the end.

**Comment by kesso1** [comment] 2017-03-06 08:31
I know how to add a workspace, the question was how to tell the Microsoft.R.Host.Broker Service, which R interpreter it has to select. Default is the r interpreter in C:\Program Files\Microsoft\MRO-3.3.2\, but it should select the interpreter in C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQL01\R_SERVICES, behause there is RevoScaleR Package installed.

**Comment by smortaz** [comment] 2017-03-06 08:48
when you connect to the broker, and the REPL starts, do you see a list of several interpreters?  if so, you can select each one by adding and # and its number at the end of the URL, eg #1, #2, #3 

or perhaps i dont quite understand the question...

**Comment by kesso1** [comment] 2017-03-06 09:57
In the Microsoft.R.Host.Broker-Log i see the following entries:
[2017-03-06 08:50:01Z] <Microsoft.R.Host.Broker.Interpreters.InterpreterManager> (T):
Auto-detecting R ...

[2017-03-06 08:50:01Z] <Microsoft.R.Host.Broker.Interpreters.InterpreterManager> (T):
R 3.3.2 detected at \"C:\Program Files\Microsoft\MRO-3.3.2\\"

[2017-03-06 08:50:01Z] <Microsoft.R.Host.Broker.Interpreters.InterpreterManager> (I):
1 interpreters configured:
[0] : Microsoft R Open (3.3.2) at "C:\Program Files\Microsoft\MRO-3.3.2\"

[2017-03-06 08:50:01Z] <Microsoft.AspNetCore.Hosting.Internal.WebHost> (D):
Hosting starting

But I don't know how to change this default interpreter...

**Comment by MikhailArkhipov** [comment] 2017-03-06 15:39
You change interpreter you connect to at the client side. The URL looks like `https://machine:5444#2` to select 3rd interpreter in the list (zero-based index). 'Default' means the one server uses when URL does not specify the interpreter index.

When you connect to remote machine, the connection outputs list of available engines like
```
[0] Microsoft R Open
[1] R 3.3.1
[2] R 3.2.2
```

and help text that tells how to construct the URL. Ex `https://machine:5444#2` will connect to R 3.2.2 above.

**Comment by MikhailArkhipov** [comment] 2017-03-06 15:42
Here is output of our test server

![image](https://cloud.githubusercontent.com/assets/12820357/23617038/7f3acff0-0240-11e7-8ab8-edfb32573aa7.png)

**Comment by MikhailArkhipov** [comment] 2017-03-07 21:52
Closing. Let us know if you still have questions.

**Closed by MikhailArkhipov** 2017-03-07 21:52 UTC

**Comment by kesso1** [comment] 2017-03-13 13:20
If we connect to the remote workspace, this is the only one that appears to choose:

Installed R versions:
	[0] Microsoft R Open (3.3.2) (Default)

But on target server there's another one installed in the path:

C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQL01\R_SERVICES

How can I manage the available interpreters on the target remote workspace.

**Comment by MikhailArkhipov** [comment] 2017-03-13 15:13
Try adding path manually in the broker config file (Microsoft.R.Host.Broker.json) similarly to certificates:

```
{
  "server.urls": "https://0.0.0.0:5444",
  "security": {
    "X509CertificateName": "CN=your-server-fully-qualified-domain-name"
  }
   "R": { 
       "Name": "path-to-64-bit-bin"
    }
}
```

**Comment by MikhailArkhipov** [comment] 2017-03-13 18:49
Corrected
```
“R” {
  “AutoDetect”: true,
  “Interpreters”: {
    “Key1”: {
       “Name1”: “BasePath1”
    },
    “Key2”: {
       “Name2”: “BasePath2”
    },
    …
}
```
AutoDetect is the default setting and can be omitted. `Key1`, `Key2` etc is what’ll go after # in the URL. `Name` is supposed to be descriptive.

**Comment by kesso1** [comment] 2017-03-14 08:55
I tried with suggestion, but now the Host Broker Service doesn't start anymore. My Host.Broker.json looks like:

{
	"server.urls": "https://0.0.0.0:5444",
	"R": {
	  "Interpreters": {
			"0": {
			   "mro": "C:\Program Files\Microsoft\MRO-3.3.2\bin\x64"
			},
			"1": {
			   "sql": "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQL01\R_SERVICES\bin\x64"
			}
		}
	}
}

**Comment by kesso1** [comment] 2017-03-14 09:12
sry i missed the double backslashes within the pathes. now the service starts again, but it seems the interpreters are not found: Host.Broker.log:

[2017-03-14 10:10:56Z] <Microsoft.R.Host.Broker.Interpreters.InterpreterManager> (T):
R 3.3.2 detected at \"C:\Program Files\Microsoft\MRO-3.3.2\\"

[2017-03-14 10:10:56Z] <Microsoft.R.Host.Broker.Interpreters.InterpreterManager> (E):
Failed to retrieve R installation data for interpreter \"0\" at \"\"

[2017-03-14 10:10:56Z] <Microsoft.R.Host.Broker.Interpreters.InterpreterManager> (E):
Failed to retrieve R installation data for interpreter \"1\" at \"\"

[2017-03-14 10:10:56Z] <Microsoft.R.Host.Broker.Interpreters.InterpreterManager> (I):
1 interpreters configured:
[0] : Microsoft R Open (3.3.2) at "C:\Program Files\Microsoft\MRO-3.3.2\"

**Comment by kesso1** [comment] 2017-03-14 09:33
json looks now as follow:
{
	"server.urls": "https://0.0.0.0:5444",
	"R": {
		"Interpreters": {
			"0": {
				"mro": "C:\\Program Files\\Microsoft\\MRO-3.3.2\\bin\\"
			},
			"1": {
				"sql": "C:\\Program Files\\Microsoft SQL Server\\MSSQL13.MSSQL01\\R_SERVICES\\bin\\"
			}
		}
	}
}

**Comment by kesso1** [comment] 2017-03-14 09:34
[2017-03-14 10:29:19Z] <Microsoft.R.Host.Broker.Interpreters.InterpreterManager> (E):
Failed to retrieve R installation data for interpreter \"0\" at \"\"

[2017-03-14 10:29:19Z] <Microsoft.R.Host.Broker.Interpreters.InterpreterManager> (E):
Failed to retrieve R installation data for interpreter \"1\" at \"\"

**Comment by int19h** [comment] 2017-03-14 09:43
Sorry, I didn't give the right format above. This is what it should look like in your case:
```json
{
"server.urls": "https://0.0.0.0:5444",
  "R": {
    "Interpreters": {
      "0": {
        "name": "MRO",
        "basePath": "C:\\Program Files\\Microsoft\\MRO-3.3.2"
      },
      "1": {
        "name": "MSSQL R Services",
        "basePath": "C:\\Program Files\\Microsoft SQL Server\\MSSQL13.MSSQL01\\R_SERVICES"
      }
    }
  }
}
```
You can use whatever you want for `name`, it's meant to be a descriptive label for display purposes and nothing more. And the paths shouldn't include the `bin\x64` bit, we add that automatically.

**Comment by kesso1** [comment] 2017-03-14 12:14
Thx, that works. Now if a user connects, there is a unauthorized exception:

Exception: The remote server returned an error: (401) Unauthorized.

The user trying to access is local administrator.

**Comment by kesso1** [comment] 2017-03-14 12:34
In Host.Broker.log: 

[2017-03-14 13:30:00Z] <Odachi.AspNetCore.Authentication.Basic.BasicMiddleware> (I):
Basic was not authenticated. Failure message: Invalid basic authentication credentials.

[2017-03-14 13:30:00Z] <Odachi.AspNetCore.Authentication.Basic.BasicMiddleware> (I):
AuthenticationScheme: Basic was challenged.

**Comment by MikhailArkhipov** [comment] 2017-03-14 16:23
User doesn't have to be local admin or even have rights to terminal server to the box. Try looking into system event log (Event Viewer -> Wingows Logs -> Security), usually there is extended information about authentication failures.

**Comment by int19h** [comment] 2017-03-14 19:00
When entering the user name, did you include the domain name before `\`? For local accounts, this should be the Windows name of the machine itself.

**Comment by kesso1** [comment] 2017-03-23 11:50
In security log are no authentication failures, just some entries with task category "Sensitive Privilege Use", but no errors. Domain name is also prefixed.

**Comment by N1h1l1sT** [comment] 2018-01-27 21:36
I have the same problem. I have an Azure Data Science Virtual Machine on Linux (Ubuntu) with R Server 9.2.1 and I've installed RTVS.
When I connect to the remote workspace from my Visual Studio 2017, I can only see 1 entry,
I'd like to add the suggestion to the JSON, but I can't find "Microsoft.R.Host.Broker.json" on the Linux VM.
How do I resolve the problem and connect to the R Server instead of the only option of R Open?

**Comment by MikhailArkhipov** [comment] 2018-01-27 22:05
RTVS cannot directly connect to R Server. These are generally unrelated products. If you want to connect to Linux on Azure you need to install remote service for Visual Studio. R on Linux can be any R, does not have to be R Server.

Please see docs here 
https://docs.microsoft.com/en-us/visualstudio/rtvs/workspaces-remote-setup#install-r-services-on-linux
Please see

**Comment by N1h1l1sT** [comment] 2018-01-27 22:24
Yeah, it can connect to other Rs besides R Server, but It definitely **can** connect to R Server as well.

If I deploy an HDInsight R Server cluster and put RTVS on its edge node, when I do the same thing from Visual Studio, it connects me to the R Server's R which has the RevoScaleR packages so I can use rx functions.

The thing is, when I try it with the Data Science VM, all it sees is the MRO.
I want to be able to use the rx packages as I can when I type "R" on that VM

P.S. I've already seen the docs link.. it doesn't help with the problem I have. It seems mostly about connecting to it in the first place.

**Comment by MikhailArkhipov** [comment] 2018-01-27 22:36
Did you try adding path to the interpreter in the broker JSON file?

**Comment by N1h1l1sT** [comment] 2018-01-27 22:43
Where is this broker file? The VM is linux but the paths mentioned here are for windows.
Where is this file on linux?

**Comment by N1h1l1sT** [comment] 2018-01-28 15:13
Okay, I just saw something that might add some additional light into this. This doesn't seem to be an RTVS problem after all.

Evidence 1: On the HDInisght R Server that it connects normally, it still says "Microsoft R Open", but the RevoScaleR package is available. So that's just how it always says it

Evidence 2: On the Data Science Virtual Machines there's a general problem with R Server's R not being available in anything else but the terminal: https://goo.gl/13WSs4

So i'm guessing the reason this doesn't work with RTVS is the same reason it doesn't work with RStudio Server and Operationalization - not an RTVS problem.

However, if you could help at all, please, do so.

**Comment by MikhailArkhipov** [comment] 2018-01-29 18:07
@karthiknadig can manual suggest interpreter configuration steps for Linux

**Comment by karthiknadig** [comment] 2018-01-29 19:30
The `JSON` config file on Ubuntu is located at `/etc/rtvs/rtvsd.config.json`. The steps are similar to windows. You should be able to find the path you need by looking at the file list for the package. Selecting the path that contains `libR.so`. For example, MRO can be found like this:
```
~$ cat /var/lib/dpkg/info/microsoft-r-open-mro-3.4.1.list | grep libR.so
/opt/microsoft/ropen/3.4.1/lib64/R/lib/libR.so
```
use `/opt/microsoft/ropen/3.4.1/lib64/R` as the `basePath`. We attempt to detect other information( like version, docs, includes) based on this path by searching installed packages.

Note: R Server on linux uses MRO as the interpreter, hence we only detect MRO. Installing R Server (or Machine Learning server) will also install MRO as a dependency. 
```
~$ dpkg --status microsoft-mlserver-packages-r-9.2.1
Package: microsoft-mlserver-packages-r-9.2.1
Status: install ok installed
Section: devel
Maintainer: revobuil@microsoft.com
Version: 9.2.1.1360
Depends: microsoft-r-open-mro-3.4.1, microsoft-r-open-mkl-3.4.1, microsoft-r-open-foreachiterators-3.4.1
Description: Microsoft Machine Learning Server
```

**Comment by N1h1l1sT** [comment] 2018-01-30 18:46
@karthiknadig thank you very much for the information.
I'm going to need a bit more assistance.

So, i've located the following paths for MRO and R Server's R:
1) `/opt/microsoft/ropen/3.4.1/lib64/R/` containing MRO.
2) `/opt/microsoft/mlserver/9.2.1/runtime/R/bin/R/` which is a symlink for `/data/mlserver/9.2.1/runtime/R/bin/R/` containing the same folders as '1)', being MRO again.
3) `/opt/microsoft/mlserver/9.2.1/bin/R/` which is a symlink for `/data/mlserver/9.2.1/bin/R/` which contains the R Server's R, and incidentally, is the path which `which R` and `which Revo64` point to.

So 3) is exactly what I need to load. So I change the JSON from the original I found on the DSVM:
`{
  "logging": { "logFolder": "/tmp" },
  "security": {
    "allowedGroup": "",
    "X509CertificateFile": "/etc/rtvs/ssl-cert-snakeoil.pfx",
    "X509CertificatePassword": "SnakeOil"
  },
  "startup": { "name": "rtvsd" },
  "urls": "https://0.0.0.0:5444"
}`

to this one:

`{
  "logging": { "logFolder": "/tmp" },
  "security": {
    "allowedGroup": "",
    "X509CertificateFile": "/etc/rtvs/ssl-cert-snakeoil.pfx",
    "X509CertificatePassword": "SnakeOil"
  },
  "startup": { "name": "rtvsd" },
  "urls": "https://0.0.0.0:5444",
  "server.urls": "https://0.0.0.0:5444",
  "R": {
    "Interpreters": {
      "0": {
        "name": "MRO",
        "basePath": "/opt/microsoft/ropen/3.4.1/lib64/R/"
      },
      "1": {
        "name": "R Server",
        "basePath": "/opt/microsoft/mlserver/9.2.1/bin/R/"
      }
    }
  }
}`

Unfortunately it did not work.
#1 fails with message:
`Connecting to R Workspace failed.
Reason: Specified R interpreter [1] was not found`
and
#0 loads, but it mentions:
`Installed R version:
    [0] Microsoft R Open '3.4.1.1347 (Default)
    [0] MRO (Default)
If you want to select specific R version, specify its id 
number in the connection URL in the form 'https://remote:5444#2'

Version of R Services on machine (1.2.31009.1007)
is lower than the version of R Tools on the local computer (1.3.31108.1213).`
so it has two [0] and both of the Defaults instead of the [0] and [1] I tried to do.

**Comment by karthiknadig** [comment] 2018-01-30 20:29
I see what is going on. The runtime is not in the dpgk package list. So the rtvs daemon is not able to find all the directories it needs. If you see the daemon log, you will see a message like `Failed to retrieve R installation data for interpreter "R Server" at "/opt/microsoft/mlserver/9.2.1/runtime/R"`. I created a bug to track this issue.

**Comment by N1h1l1sT** [comment] 2018-01-30 20:38
Thank you, that is great!

If you'd like to reproduce the issue I can provide a step by step guide to do so. In case that's not necessary, I'll just mention it now on a higher: On any Azure Linux "DSVM" and Linux Machine Learning Server 9.2.1, when RTVS is installed this always happens.

Also, where could I find the rtvs daemon log (as you've probably already understood, I don't have much experience with Linux, but I try to make do)

**Comment by gwd999** [comment] 2020-01-06 16:51
Hi - really enjoy the extension with VSC on Windows 10 - so I tried to get it running under WSL2. 
Even though I am sticking to the above instructions (I added .NET Core 2.1, I put Microsoft.R.Host.Broker.Config.json file with content from above [only included "autodetect":"false", as well, even included Windows paths next to the WSL2 custom build R (path) I am tryng to fire up here, so there is no '3.4.4-1ubuntu1' around with my setup] to .vscode-server/extensions/mikhail.../ls/ ) R tools under VS Code on WSL2 (Ubuntu 18.04 LTS). Still it will only return "Unable to start R process" and utterly ignores any Interpreters defined in ...Host.Broker:Config.json 
ie Output window in VSC only shows: Available R interpreters ... [0] CRAN R '3.4.4-1ubuntu1' ??? Any ideas, why Broker.Config settings are being ignored ...

**Comment by Direct-A** [comment] 2020-03-05 10:46
@gwd999 I have the same problem, have you solve it? and how to solve it?
