### ISSUE TITLE
feedback about the latest RTVS update

### ISSUE THREAD

**Issue by leox31** [Microsoft/RTVS#3016] opened 2017-01-19 12:04 UTC
Hello,
When switching between R interpreters,  it appears any data frames ( objects) being created in the global environment gets deleted.  For example, using R client to create a data.frame from an xdf file, it will be deleted from the global environment when switching to standard R to use the data for further analysis.
I am wondering if such issue can be resolved by ensure any objects created in one interpreter is transverse across all interpreters.
 
Thank  #you

Please briefly describe what you were doing that led to the issue, if applicable:

...

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.14393.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.6.30105.2202, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    Microsoft R Open (3.3.2): C:\Program Files\Microsoft\MRO-3.3.2\

**Comment by MikhailArkhipov** [comment] 2017-01-19 18:00
This is by design. Switching interpreters loads completely different environments (and starts different processes hosting R. If you want to reuse data, you have to save workspace manually in R (ex http://www.statmethods.net/interface/workspace.html) and load .rdata into the new interpreter.

**Comment by Hong-Revo** [comment] 2017-01-20 09:30
This is currently logged at #2920: presumably the next build of RTVS will display a warning before switching.

**Comment by jflam** [comment] 2017-01-23 17:24
Yes. This will show up in the next update. Closing this issue now. Please re-open again if you have additional feedback. Thanks!

**Closed by jflam** 2017-01-23 17:24 UTC
