### ISSUE TITLE
dev15: ?for doesnt give help...

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#2131] opened 2016-07-29 22:37 UTC
![image](https://cloud.githubusercontent.com/assets/742484/17265261/65da0652-55a2-11e6-9c24-c68e00e181f7.png)

**Comment by int19h** [comment] 2016-07-29 22:39
Not legal R syntax. You need to quote the "for".

**Comment by int19h** [comment] 2016-07-29 22:42
Or else you need to spell the loop out completely, such that it is syntactically valid, e.g. this works:
```r
?for(x in y){}
```
Basically, `?` is an operator in R, and for it to run, your expression has to be syntactically valid R.

**Comment by MikhailArkhipov** [comment] 2016-07-29 22:42
Same as in RGUI

**Comment by MikhailArkhipov** [comment] 2016-07-29 22:43
And in RS. Closing as by design

**Closed by MikhailArkhipov** 2016-07-29 22:43 UTC

**Comment by smortaz** [comment] 2016-07-30 13:21
Ah. Thx
