### ISSUE TITLE
assert when expanding node in VE

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#1453] opened 2016-04-05 21:24 UTC
imported bike data from examples from github.

expanded one of the children.

got:

---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Internal debugger evaluation rtvs:::describe_children("as.environment(\".GlobalEnv\")$Bike_Rental_UCI_Dataset-2222$mnth", base::sys.frame(0), base::c('expression', 'kind', 'repr', 'repr.str', 'type', 'classes', 'length', 'slot_count', 'attr_count', 'dim', 'flags'), 20, 100) failed: ; 'Error in 2222$mnth : $ operator is invalid for atomic vectors
'

   at Microsoft.R.Debugger.DebugSession.<InvokeDebugHelperAsync>d__26.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolea......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by int19h** [comment] 2016-04-05 21:26
This is a dupe of #1408. But given this scenario, we might want to reprioritize it for 0.3, since the fix is very simple, and dataframes with column names like these aren't uncommon.

**Closed** 2016-04-05 21:26 UTC
